
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: rails_hotwire_app_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost

test:
  <<: *default
  database: rails_hotwire_app_test

production:
  <<: *default
  database: rails_hotwire_app_production
